### ISSUE TITLE
`build-plugin-rax-compat-react` not work with `antd-mobile`

### ISSUE THREAD

**Issue by lucifer1004** [raxjs/rax-scripts#103]
## Error message

(undefined) ./node_modules/antd-mobile/es/action-sheet/index.js
Module not found: Can't resolve 'react-dom' in '...'

## Configuration (`build.json`)

```json
{
  "plugins": [
    [
      "build-plugin-rax-app",
      {
        "targets": ["web", "wechat-miniprogram"]
      }
    ],
    "build-plugin-rax-compat-react"
  ]
}
```

**Comment by yacheng** [comment]
我看下

**Comment by yacheng** [comment]
跟进 pr https://github.com/raxjs/rax-scripts/pull/114
