### ISSUE TITLE
Style for Rax components is not load correctly when disable inlineStyle

### ISSUE THREAD

**Issue by chenjun1011** [raxjs/rax-scripts#133]
When disable inlineStyle in `build.json`, styles for `rax-text` & `rax-view` can not be built to  css file. (both spa and mpa are not work correctly)

```json
{
  "plugins": [
    [
      "build-plugin-rax-app",
      {
        "targets": ["web"]
      }
    ]
  ],
  "inlineStyle": false
}

```

![image](https://user-images.githubusercontent.com/1303018/71949447-80335480-320e-11ea-8c67-52664cc9d5dc.png)

**Comment by yacheng** [comment]
问题的原因是示例项目的代码没有支持 inlineStyle，我本周内修复一下

**Comment by fyangstudio** [comment]
inlineStyle 关闭后，还需修改样式引用，不是什么都不需要改的。
比如：
```
<Image
      style={styles.logo}
      source={{
        uri: '//gw.alicdn.com/tfs/TB1MRC_cvb2gK0jSZK9XXaEgFXa-1701-1535.png',
      }}
    />
```
style=xxx 要改成 className= xxx
```
<Image
      className="logo"
      source={{
        uri: '//gw.alicdn.com/tfs/TB1MRC_cvb2gK0jSZK9XXaEgFXa-1701-1535.png',
      }}
    />
```

**Comment by chenjun1011** [comment]
> inlineStyle 关闭后，还需修改样式引用，不是什么都不需要改的。
> 比如：
> 
> ```
> <Image
>       style={styles.logo}
>       source={{
>         uri: '//gw.alicdn.com/tfs/TB1MRC_cvb2gK0jSZK9XXaEgFXa-1701-1535.png',
>       }}
>     />
> ```
> 
> style=xxx 要改成 className= xxx
> 
> ```
> <Image
>       className="logo"
>       source={{
>         uri: '//gw.alicdn.com/tfs/TB1MRC_cvb2gK0jSZK9XXaEgFXa-1701-1535.png',
>       }}
>     />
> ```

这个我看现在工程上已经处理了 构建时会转成 className

**Comment by fyangstudio** [comment]
@yacheng 有个问题是 SPA 下，设置 inlineStyle false，rax-text rax-view 这些组件的 CSS 会丢失

**Comment by yacheng** [comment]
这里有两个问题，一个是 rax-generator 对 className 的支持问题，还有一个是 build-plugin-rax-app 对于组件样式的引入写死了  isMultiple 判断条件。需要一起改掉

**Comment by fyangstudio** [comment]
> @yacheng 有个问题是 SPA 下，设置 inlineStyle false，rax-text rax-view 这些组件的 CSS 会丢失

[https://github.com/raxjs/rax-scripts/pull/132](https://github.com/raxjs/rax-scripts/pull/132) 已修复
