### ISSUE TITLE
rax scripts 体验问题

### ISSUE THREAD

**Issue by boiawang** [raxjs/rax-scripts#134]
![image](https://user-images.githubusercontent.com/6340730/71949666-5dee0680-320f-11ea-87e5-dea9276d359d.png)

- 不支持 help 查看具体参数
- 不能定制端口
- 启动的时候端口不会自动 +1

**Comment by wssgcg1213** [comment]
![image](https://user-images.githubusercontent.com/3922719/71950018-b96cc400-3210-11ea-8650-f9e98b069403.png)

- Project is running at http://0.0.0.0:9999/ 但是下面的 info WEBPACK Starting the development server at:
info     http://localhost:9999/

- webpack output is served from `undefined`

**Comment by wssgcg1213** [comment]
![image](https://user-images.githubusercontent.com/3922719/71950108-14062000-3211-11ea-8a5b-c124c906beb8.png)

**Comment by andycall** [comment]
功能都有了，可以关闭了
