### ISSUE TITLE
存在内存泄露

### ISSUE THREAD

**Issue by wssgcg1213** [raxjs/rax-scripts#140]
RT, 可能跟 sourceMap 有关
![image](https://user-images.githubusercontent.com/3922719/72083851-6cd2d700-333d-11ea-949c-7caf708e2efd.png)

**Comment by yacheng** [comment]
问题复现路径是什么

**Comment by wssgcg1213** [comment]
64位下强制gc需要达到内存~1.4G左右才会触发, 最好的排查方式是记录堆内存变化   https://marmelab.com/blog/2018/04/03/how-to-track-and-fix-memory-leak-with-nodejs.html

**Comment by chenjun1011** [comment]
fixed in https://github.com/raxjs/rax-scripts/pull/377
