### ISSUE TITLE
@rax-types/rax 类型冲突

### ISSUE THREAD

**Issue by aladdin-add** [raxjs/rax-scripts#16]
https://github.com/raxjs/rax-scripts/blob/9a75e1c3af2544513330cfe40012efd58f8f33cb/packages/scripts-core/package.json#L19

auto-bind 依赖的@types/react 和 @rax-types/rax 类型冲突。refs: https://github.com/sindresorhus/auto-bind/issues/16

**Comment by Orange-C** [comment]
looking for replacement……
