### ISSUE TITLE
[BUG] windows 上启动服务后资源找不到

### ISSUE THREAD

**Issue by SoloJiang** [raxjs/rax-scripts#169]
复现步骤：
用 windows 初始化项目，选择 Web 作为投放端，`npm start`:
![image](https://user-images.githubusercontent.com/14757289/72971597-efab6580-3e04-11ea-9ada-bf23ec550a5b.png)

**Comment by chenjun1011** [comment]
build-plugin-rax-app@2.1.0-beta.2 beta版本，可以作为验证

**Comment by chenjun1011** [comment]
已修复
