### ISSUE TITLE
建议 document 渲染时取消默认添加 <!DOCTYPE html>

### ISSUE THREAD

**Issue by demohi** [raxjs/rax-scripts#185]
背景：

rax-app 使用 jsx 作为 document 的模板语言，目前构建产物最前面默认添加了<!DOCTYPE html>
[相关代码](https://github.com/raxjs/rax-scripts/blob/master/packages/build-plugin-rax-app/src/plugins/UniversalDocumentPlugin.js#L104)
```js
        // get document html string
const pageSource = `<!DOCTYPE html>${renderToString(DocumentContextProviderElement)}`;
```

这样就对模板能力做了限制（和 ejs 能力不对等)，比如我想渲染成非 html 就很麻烦。

建议：

 1. 取消默认添加 <!DOCTYPE html>
 2. rax-document 提供 DOCTYPE 组件（这个标签比较特别，非闭合）
 3. 目前如何写一个类似 DOCTYPE组件，也可以在文档里面描述一下，不然使用 jsx 作为模板语言，写起来有些痛苦

**Comment by wssgcg1213** [comment]
agree, DOCTYPE 不仅仅一种表达形式(`<!DOCTYPE html>`), 还有其他(XHTML/HTML4.01), 限制死了不太妥  cc @chenjun1011
