### ISSUE TITLE
document 使用 jsx 开发，如何友好支持 script 代码

### ISSUE THREAD

**Issue by demohi** [raxjs/rax-scripts#197]
```
<script>
    const  test = {
       title: "test title"
   }
</script>
```
构建时，会被转义
如果使用 dangerouslySetInnerHTML 与其他模板相比，体验太不友好
希望可以给一个方案

**Comment by chenjun1011** [comment]
在 JSX 里，这个限制很难去除，比如上面示例代码里的 `{}` 在 JSX 编译的时候就会被认为里面的内容是表达式。所以只能通过 dangerouslySetInnerHTML 来实现这类需求。
