### ISSUE TITLE
组件工程中，用户只选择小程序端时，构建出的产物在使用时报找不到依赖

### ISSUE THREAD

**Issue by ChrisCindy** [raxjs/rax-scripts#222]
- 描述
组件工程中，用户只选择小程序端时，构建时不会创建 lib/index.js 文件，导致 package.json 的 main 字段对应文件不存在，这样在小程序中使用时会报找不到依赖

- 解决办法
用户只选择小程序端时，构建时也默认给 lib 目录下创建一个空的 index.js 文件

**Comment by andycall** [comment]
空白文件？不构建？

**Comment by ChrisCindy** [comment]
> 空白文件？不构建？

@andycall 可以构建也可以不构建，但是要确保 lib/index.js 文件存在。在小程序中该文件不会被用到，但是由于其是 package.json 中 main 字段对应的地址，因此需要用其来寻址

**Comment by yacheng** [comment]
空的 index 文件感觉没有什么实际作用，对于安装该组件的同学反而是一种误导，感觉这种情况可以修改 main 的指向
