### ISSUE TITLE
调整 MPA 开启方式

### ISSUE THREAD

**Issue by chenjun1011** [raxjs/rax-scripts#228]
问题： 目前 SPA 和 MPA 在开启方式上是不对等的，从 SPA 切换到 MPA 需要引入单独的插件，容易给用户造成理解成本

解决方案：将 MPA 的开启方式调整到 build-plugin-rax-app 内

```
{
  "plugins": [
    [
      "build-plugin-rax-app",
      {
        "targets": ["web"],
        "type": "mpa" // spa
      }
    ]
  ]
}

```

改动点：
1. 抽取 MPA 相关配置到  rax-multi-page-config 
2. build-plugin-rax-app/build-plugin-rax-multi-pages 依赖  rax-multi-page-config  进行多页配置， 同时 set 多页标志到插件体系中
3. 其他插件 ssr/def 去除对 build-plugin-rax-multi-pages 的直接判断，改为判断多页标志

**Comment by fyangstudio** [comment]
4 build-plugin-rax-multi-pages  检测到有多页标志，waring 提示最新使用方法

**Comment by yacheng** [comment]
2. 当 build-plugin-rax-app 存在 appType 标记的时候跳过 build-plugin-rax-multi-pages 的实现
当 build-plugin-rax-app 不存在 appType 标记时，使用 build-plugin-rax-multi-pages 的实现

**Comment by yacheng** [comment]
3. build-plugin-rax-multi-pages  需要兼容 appType 是否存在的场景
对于其他插件需要有过度版本，支持 multi-pages 插件名称与 appType 的判断兼容

**Comment by yacheng** [comment]
1、抽取 MPA 相关配置到 rax-multi-page-config
2、build-plugin-rax-app/build-plugin-rax-multi-pages 依赖 rax-multi-page-config 进行多页配置， 同时 set 多页标志到插件体系中
3、其他插件 ssr/def 去除对 build-plugin-rax-multi-pages 的直接判断，改为判断多页标志，支持 multi-pages 插件名称与标志位的判断兼容
4、build-plugin-rax-multi-pages 检测到有多页标志，waring 提示最新使用方法，存在多标志位的时候跳过当前插件的实现


标志位命名：appType
线上兼容方案：老的插件名称判断与标志位判断兼容
