### ISSUE TITLE
[BUG] 组件工程，如果 targets 不添加小程序相关，不会构建出 lib 目录

### ISSUE THREAD

**Issue by SoloJiang** [raxjs/rax-scripts#234]
- 如果 targets 为 `['web', 'weex']` 不会构建出 `lib` 目录
- 如果添加了 `miniapp`，会同时构建出 `lib/miniapp` `lib/miniapp-wechat`，预期应该只有 `lib/miniapp`

**Comment by SoloJiang** [comment]
这个问题比较复杂：组件工程 `src` 下面的除了 `index.js` 的系列的依赖以外，其他的都会平行复制到 `lib`，这个操作是为了满足原生小程序组件的需求，但是如果用户 `targets` 里包含了 `miniapp`，即此时需求是既要保留原生小程序的实现，又要有小程序的产物（小程序编译时和运行时结合的情况），从而产生的命名的冲突是否需要提示给用户？

**Comment by SoloJiang** [comment]
以及 @ChrisCindy  的 pr 修复的是第一个问题，第二个问题还需要 @yacheng 看下

**Comment by yacheng** [comment]
build.json

```
{
  "plugins": [
    [
      "build-plugin-rax-component",
      {
        "type": "rax",
        "targets": ["web", "miniapp"]      
      }
    ]  
  ]
}
```

插件版本

```
"@alib/build-scripts": "^0.1.0",
"build-plugin-rax-component": "^0.2.1",
```

实际测试，并不会生成 lib/miniapp-wechat 目录

**Comment by ChrisCindy** [comment]
@yacheng @SoloJiang 所说的实际上是另一个问题，以 rax-canvas 为例，当 src 下存在 miniapp 目录并且代码是 TS 时，编译后会直接将 miniapp 目录平移到 lib 目录，而无视 targets 配置。个人感觉这个问题不是很严重，比较边界。

**Comment by SoloJiang** [comment]
> build.json
> 
> ```
> {
>   "plugins": [
>     [
>       "build-plugin-rax-component",
>       {
>         "type": "rax",
>         "targets": ["web", "miniapp"]      
>       }
>     ]  
>   ]
> }
> ```
> 
> 插件版本
> 
> ```
> "@alib/build-scripts": "^0.1.0",
> "build-plugin-rax-component": "^0.2.1",
> ```
> 
> 实际测试，并不会生成 lib/miniapp-wechat 目录

https://github.com/raxjs/rax-components/pull/150 参见这个 pr 的 rax-canvas，`build.json` 中 `targets` 只保留 `miniapp`
