### ISSUE TITLE
小程序静态编译在微信中语法报错

### ISSUE THREAD

**Issue by KevLeong** [raxjs/rax-scripts#250]
微信小程序 moustache 语法不支持 key value 形式，如最下图
步骤:
1. npm init rax 
2. 选择微信小程序
3. run
![image](https://user-images.githubusercontent.com/26003213/77384516-8de58880-6dc0-11ea-9865-6b2bfcaedb60.png)

**Comment by SoloJiang** [comment]
微信小程序需要将对象赋值给变量

**Comment by SoloJiang** [comment]
后面会研究一下怎么优化这部分的体验

**Comment by KevLeong** [comment]
> 微信小程序需要将对象赋值给变量，本身节点上不支持直接写对象

嗯，我的理解是下面这种不支持👇
```javascript
<Image source={{ uri: 'link' }} />
```
但现在是这种也会有问题👇
```javascript
const source = { uri: 'link' };
<Image source={source} />
```

**Comment by SoloJiang** [comment]
我下周给个方案出来，这里面主要涉及到作用域的问题

**Comment by KevLeong** [comment]
https://github.com/raxjs/rax-scripts/pull/254
麻烦看下这个PR能否解决哈
