### ISSUE TITLE
Unable to install packages through `def init rax`

### ISSUE THREAD

**Issue by valkurash** [raxjs/rax-scripts#299]
Error in installing dependencies occurs when run `def init rax`
Console log:
![image](https://user-images.githubusercontent.com/3253694/79558878-88bce600-80ad-11ea-9e38-d5d3649351e3.png)
When then try to run `tnpm install` after project initialisation there is also error:
![image](https://user-images.githubusercontent.com/3253694/79559212-ff59e380-80ad-11ea-9785-2566d91af316.png)

**Comment by chenjun1011** [comment]
That's a problem related to npm, it's about the cache that get corrupt. 

try `npm cache clean --force`

see: https://stackoverflow.com/questions/47675478/npm-install-errorunexpected-end-of-json-input-while-parsing-near-nt-webpack
