### ISSUE TITLE
inlineStyle 关闭后，与 filename 配置冲突

### ISSUE THREAD

**Issue by demohi** [raxjs/rax-scripts#307]
inlineStyle设置为 false 时，如果同时配置 filename，对 index.css无效

```
config.output.filename('pages/[name].js');
```

![image](https://user-images.githubusercontent.com/1209159/80303371-86136c80-87e2-11ea-98a4-1dac99122b1d.png)

**Comment by yacheng** [comment]
build-plugin-rax-app 标准构建结果是分端维度生成构建产物。业务上对于构建产物的目录重新组织建议在独立插件中进行文件的拷贝移动。最终生成的 cdn 地址可以通过修改 publicPath 对应目录重新组织后的路径
