### ISSUE TITLE
现针对小程序端独有的配置，在 build.json 中怎么配置？

### ISSUE THREAD

**Issue by balloonzzq** [raxjs/rax-scripts#34]

**Comment by yacheng** [comment]
插件的配置建议放到每个插件里，不去污染全局配置

**Comment by fyangstudio** [comment]
`
{
"plugins": [
    [
      "rax-plugin-app",
      {
        "targets": [
          "web"
        ],
        "web": {
        },
        "miniapp":{
        }
      }
    ]
]
}
`

**Comment by ChrisCindy** [comment]
赞成 @fyangstudio 的写法，大家还有其他意见吗？

**Comment by SoloJiang** [comment]
+1

**Comment by Orange-C** [comment]
嗯就这样吧
