### ISSUE TITLE
工程日志优化

### ISSUE THREAD

**Issue by chenjun1011** [raxjs/rax-scripts#44]
1.  默认工程会有如下报错

![image](https://user-images.githubusercontent.com/1303018/67947559-dbe5ce00-fc1e-11e9-8c40-b47e17205892.png)

2. 不同插件构建日志重复打印

rax-plugin-app 和 rax-plugin-multi-pages 在每次编译完后都会重复打印如下日志，只要保留一个就行了

![image](https://user-images.githubusercontent.com/1303018/67947667-1d767900-fc1f-11e9-958b-8c08e723d29b.png)

3. SSR 工程下  JSX+ 的日志重复打印

**Comment by Orange-C** [comment]
工程核心后续对插件的log再出一个专门的优化方案

**Comment by wssgcg1213** [comment]
1 和 3 应该都解了, 2 的问题和 https://github.com/alibaba/rax/issues/1579 重复, 所以关闭这个 issue
