### ISSUE TITLE
feature: 初始化时候 支持跳过默认的选择

### ISSUE THREAD

**Issue by tao1991123** [raxjs/rax-scripts#456]
因为我是用了 自定义模板初始化项目。`npm init rax demo --template xxxxxx`  
初始化的时候, 会让用户选择两个选项。问题在于 我自定义模板中 这两个问题是的答案写死的。
无论我这些  web 还是 miniapp 或是其他的选项。初始化出来的项目都与该两个选项无关。给用户造成误解。

![image](https://user-images.githubusercontent.com/9708135/96552581-864e7980-12e6-11eb-8824-a5437ce0cc64.png)
![image](https://user-images.githubusercontent.com/9708135/96552614-8f3f4b00-12e6-11eb-9356-cd008d8b20cd.png)
所以期望能增加参数, 在初始化项目的时候跳过对默认选项的选择

**Comment by SoloJiang** [comment]
https://github.com/raxjs/rax-scripts/pull/470

**Comment by SoloJiang** [comment]
可以通过 `-s` 或者 `--skip-ask` 跳过询问机制
