### ISSUE TITLE
[Enhance]: bundle 体积优化

### ISSUE THREAD

**Issue by SoloJiang** [raxjs/rax-scripts#468]
- [x] 状态管理可以设置关闭
- [x] lite 模式，不引入框架中台运行时任意依赖（不执行 runApp）
- [x] polyfill 按需加载
   - [x] `injectBabel` 文档移除，保留兼容该能力？
   - [x] 新增 `useBuiltIns` 字段，默认为 `usage`？

**Comment by chenbin92** [comment]
## 现有方案

1. 默认情况下会注入 `core-js/stable` 和 `regenerator-runtime/runtime`，根据 `targets` 配置的兼容浏览器进行 polyfill;
2. 开发类库项目，可以将配置设置为 `runtime`;
3. 如果想手动 polyfill，可以将配置设置为 false，工程将不会进行自动的 polyfill。

支持的配置如下：

`"runtime" | "ployfill" | false`，defaults to `ployfill`.

```json
{
  "injectBabel": false
}
```

## 改进方案

> 支持更简单的按需 polyfill，以及为最小化包体积优化过的配置。

支持的配置如下：

`"entry" | "usage" | false`，defaults to `entry`.

- `usage`：根据源代码中出现的语言特性和目标环境自动引入需要的 polyfill（最小化引入）
- `entry`：根据入口引入目标环境的所有 polyfill（全量引入）
- `false`：不自动添加 polyfill（无引入）

说明：

1. 原 `polyfill` 和 `runtime` 配置项需废弃，并给出提示；
2. 当配置 `useBuiltIns: 'usage'` 时，意味着如果其中一个依赖需要特殊的 polyfill，默认情况下 Babel 无法将其检测出来。因此需要通过 `compileDependencies` 选项进行配置。

改动：

- rax-app：默认使用 `useBuiltIns: 'usage'` 策略；
- icejs：默认使用 `useBuiltIns: 'entry'` 策略。

---

## 一些概念

### @babel/preset-env

一组预设的智能的 babel 插件。

> 注意：@babel/preset-env 不支持 stage-x 的插件

babel 维护了一份[语法支持度](https://github.com/babel/babel/blob/master/packages/babel-compat-data/data/plugins.json) 的数据源，用于判断浏览器对新语法的支持情况，以及这些语法到 babel 插件和 core-js polyfills 的映射。

`@babel/preset-env` 接受指定目标环境进行 babel 编译，icejs 工程默认支持度如下：

```json
{
  "targets": "last 2 versions, Firefox ESR, > 1%, ie >= 9, iOS >= 8, Android >= 4",
}
```

#### 配置参数

**`targets`**

用于配置项目支持的目标环境。

> 注意：如果不指定 targets，@babel/preset-env 会将所有的 ECMAScript 2015+ 代码按照默认的配置去转换

`string | Array<string> | { [string]: string }`，默认为 `{}`。

```js
{
  "targets": {
    "chrome": "58",
    "ie": "11"
  }
}
```

targets 支持指定 `esmodules`，当指定 esmodules 后将忽略浏览器目标环境。

```js
{
  "targets": {
    "esmodules": true
  }
}
```

**useBuiltIns**

用于配置项目进行 polyfill 的处理方式。

> 注意：@babel/polyfill 在 Babel 7.4.0 已被废弃, 推荐使用 core-js

`"usage" | "entry" | false`, defaults to `false`.

[详见](https://babeljs.io/docs/en/babel-preset-env#usebuiltins)

**modules**

开启将 ES6 模块语法转换为其他模块语法。设置为 false 将不转换模块。

`"amd" | "umd" | "systemjs" | "commonjs" | "cjs" | "auto" | false`，默认为 `"auto"`。

**更多配置**

[详见](https://babeljs.io/docs/en/babel-preset-env#options)

**Comment by imsobear** [comment]
polyfill 下除了 useBuiltIns 还有其他字段吗？

**Comment by chenbin92** [comment]
目前就算全量也只引入了 `core-js/stable` 的稳定功能 polyfill，是不是存在按需引入其他的 https://github.com/zloirock/core-js#commonjs-api

```json
{
   "polyfill": {
     "imports": []
   },
}
```

**Comment by SoloJiang** [comment]
`injectBabel` 这个配置和 `useBuiltIns ` 存在优先级的关系

**Comment by chenbin92** [comment]
内部做检查不能同时存在两个，推荐使用 `polyfill` 字段进行配置

**Comment by SoloJiang** [comment]
ok 没啥问题

**Comment by SoloJiang** [comment]
## 最终结论
`imports` 不需要，`polyfill` 支持两种数据类型：`string/object`

## 现有方案

1. 默认情况下会注入 `core-js/stable` 和 `regenerator-runtime/runtime`，根据 `targets` 配置的兼容浏览器进行 polyfill;
2. 开发类库项目，可以将配置设置为 `runtime`;
3. 如果想手动 polyfill，可以将配置设置为 false，工程将不会进行自动的 polyfill。

支持的配置如下：

`"runtime" | "ployfill" | false`，defaults to `ployfill`.

```json
{
  "injectBabel": false
}
```

## 改进方案

> 支持更简单的按需 polyfill，以及为最小化包体积优化过的配置。

支持的配置如下：

`"entry" | "usage" | false`，defaults to `entry`.

```json
{
   "polyfill": "usage",
   "compileDependencies": []
}
```

- `usage`：根据源代码中出现的语言特性和目标环境自动引入需要的 polyfill（最小化引入）
- `entry`：根据入口引入目标环境的所有 polyfill（全量引入）
- `false`：不自动添加 polyfill（无引入）

说明：

1. 原 `polyfill` 和 `runtime` 配置项需废弃，并给出提示；
2. 当配置 `polyfill: 'usage'` 时，意味着如果其中一个依赖需要特殊的 polyfill，默认情况下 Babel 无法将其检测出来。因此需要通过 `compileDependencies` 选项进行配置。

改动：

- rax-app：默认使用 `polyfill: 'usage'` 策略；
- icejs：默认使用 `polyfill: 'entry'` 策略。
