### ISSUE TITLE
[feature]根据浏览器版本，差异化构建

### ISSUE THREAD

**Issue by why-3** [raxjs/rax-scripts#472]
随着现在浏览器能力的不断升级，很多现代浏览器都已经支持es6语法，针对这部分浏览器，我们没有必要继续使用编译后es5的代码，这样既会增加代码体积，增加网络传输时间，还会增加parse和解析时间。
所以我们应该在构建层面，支持同时构建出es5和es6版本的文件，然后在CDN侧，由开发者根据一定的规则去转发不同的文件

**Comment by chenjun1011** [comment]
之前我们做过测试，es5 和 es6 的构建产物体积差异不大（因为 rax 工程没有默认引入 polyfill），这样做给工程带来的复杂度反而上升了

可以看一下你们业务上的具体数据吗？比如从 es5 到 es6 体积可以优化多少？

**Comment by why-3** [comment]
我试了下，正常构建后是400K，通过es6构建后是360K，如果算上GZIP的话，确实节省的体积不是很多。。
